services:
  gateway:
    build:
      context: ./gateway-api
    container_name: databricks-gateway
    ports:
      - "8000:8000"
    command: /bin/sh -lc "uvicorn app.main:app --host 0.0.0.0 --port 8000 ${UVICORN_CMD_ARGS:-}"
    env_file:
      - ./gateway-api/.env
    restart: unless-stopped
